### ISSUE TITLE
Main Example

### ISSUE THREAD

**Issue by rissem** [share/ShareJS#392]
Ran into a couple issues when I try to run the main example (`examples/server.coffee`)

First, I was started form a checked out version of the ShareJS repo, and was able to run the example server, but it did not work because the `dist` directory had not been created and populated. Not a huge deal, but it'd be a nice if the README covered that.

After that, I followed the instructions a little closer starting from `npm install share` instead of a git checkout and received the following error

```
Error: Cannot find module 'browserchannel'
  at Function.Module._resolveFilename (module.js:336:15)
  at Function.Module._load (module.js:278:25)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/sharejs-test/node_modules/share/examples/server.coffee:3:18)
  at Object.<anonymous> (/sharejs-test/node_modules/share/examples/server.coffee:2:1)
  at Module._compile (module.js:460:26)
```

**Comment by rissem** [comment]
Also should have mentioned, I was easily able to create the `dist` directory by running `npm run build`
