### ISSUE TITLE
Error: `make` failed with exit code: 2

### ISSUE THREAD

**Issue by ardykukuh** [share/ShareJS#412]
error node-gyp when i run : "npm install"
so confusing. anybody help me please ? 

this is the script error : 

11 warnings and 17 errors generated.
make: *** [Release/obj.target/hiredis/src/hiredis.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/kukuh/project/ShareJS/node_modules/hiredis
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

> share@0.7.40 prepublish /Users/kukuh/project/ShareJS
> make

**Comment by aslakhellesoy** [comment]
You should probably ask the maintainers of the hiredis npm module about this

**Comment by Jigoreyescanan** [comment]
> error node-gyp when i run : "npm install" so confusing. anybody help me please ?
> 
> this is the script error :
> 
> 11 warnings and 17 errors generated. make: *** [Release/obj.target/hiredis/src/hiredis.o] Error 1 gyp ERR! build error gyp ERR! stack Error: `make` failed with exit code: 2 gyp ERR! stack at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23) gyp ERR! stack at emitTwo (events.js:106:13) gyp ERR! stack at ChildProcess.emit (events.js:191:7) gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12) gyp ERR! System Darwin 16.0.0 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" gyp ERR! cwd /Users/kukuh/project/ShareJS/node_modules/hiredis gyp ERR! node -v v6.11.2 gyp ERR! node-gyp -v v3.4.0 gyp ERR! not ok
> 
> > share@0.7.40 prepublish /Users/kukuh/project/ShareJS
> > make

What is this error ?
