### ISSUE TITLE
Cannot read property 'handle' of undefined

### ISSUE THREAD

**Issue by harshendra181** [share/ShareJS#413]
C:\Windows\System32>coffee D:\September2017\Sharejs\ShareJS-master\examples\serv
er.coffee
TypeError: Cannot read property 'handle' of undefined
    at Function.app.use (D:\September2017\Sharejs\ShareJS-master\node_modules\co
nnect\lib\proto.js:75:30)
    at Object.<anonymous> (D:\September2017\Sharejs\ShareJS-master\examples\serv
er.coffee:72:11)
    at Object.<anonymous> (D:\September2017\Sharejs\ShareJS-master\examples\serv
er.coffee:2:1)
    at Module._compile (module.js:570:32)
    at Object.exports.run (C:\Users\harshs\AppData\Roaming\npm\node_modules\coff
ee-script\lib\coffee-script\coffee-script.js:173:23)
    at compileScript (C:\Users\harshs\AppData\Roaming\npm\node_modules\coffee-sc
ript\lib\coffee-script\command.js:224:29)
    at compilePath (C:\Users\harshs\AppData\Roaming\npm\node_modules\coffee-scri
pt\lib\coffee-script\command.js:174:14)
    at Object.exports.run (C:\Users\harshs\AppData\Roaming\npm\node_modules\coff
ee-script\lib\coffee-script\command.js:98:20)
    at Object.<anonymous> (C:\Users\harshs\AppData\Roaming\npm\node_modules\coff
ee-script\bin\coffee:15:45)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

can any body help

**Comment by kutyepov** [comment]
Were there any errors when you installed dependencies? (ran `npm install`). 
I just checked, this example works fine on OS X.

Also, you may want to checkout https://github.com/share/sharedb, which is a new ShareJS.
